### ISSUE TITLE
Removing Android foreground notifications from task bar.

### ISSUE THREAD

**Issue by emc2spider** [AppGyver/PushNotifications#8]
When the app is in foreground and a new notification arrives it gets processed as expected, but it also appears on the task bar.

Tapping on the task bar to clear the notification, the background notification handler callback fires with `coldstart=true` and the splash screen appears freezing the app.

I need to know if there's a way to remove programmaticaly the notification from the task bar?

**Comment by harsaharsa** [comment]
Sounds like a bug, we'll see what can be done!

**Comment by fidoboy** [comment]
Hi, i can confirm the bug/issue that @emc2spider is reporting. The notification is being received in both task bar and also in app. 

I'm sorry for the off topic, but it could be very helpful for me if @emc2spider can explain how are you using the plugin, cause i'm also having problems to receive the push message when my app is foreground. My app ALWAYS receive the push message in task bar (both foreground and background mode) but in foreground does not always work. The plugin is being initialized and listened (both events) from a single webView that is NOT active/visible in the appgyver app and i suspect that this is where the problem is; so, can you please, explain a bit more about your workflow and if the plugin is working fine in your android app?

**Comment by fidoboy** [comment]
Ok, forget about my issue, i've solved the problem. It was on my code, it was very difficult cause steroids.logger.log is not working and this makes harder to debug and locate issues... Anyway, the task bar bug when app is foreground already exists

**Comment by emc2spider** [comment]
@fidoboy glad to know you solved it. As for the steroids.logger.log I have been using standard javascript console.log checking it through chrome://inspect/#devices, requires having the device connected but you're not blind anymore :)

**Comment by fidoboy** [comment]
Also i've noticed that timestamp and uuid are note very effective to remove duplicated notifications. I'm receiving the same push three times, with same timestamp but different uuid. It seems to be related with the collapse_key ended with the message. When i use a common collapse_key it seems to work fine and no duplicated push notifications are received, but when i use random collapse_key (it's needed in order to ensure the delivery) then i receive the same push three times. As @emc2spider pointed, they are being displayed both in task bar and also in app...

**Comment by emc2spider** [comment]
@harsaharsa I think I fixed this.

Searching through the plugin code and the actual functionality experienced, I figured the PushHandlerActivity was trying to reload the main activity when it was already running and this was what froze the app. So I added a SINGLE_TOP flag to the intent.

Line 75 of PushHandlerActivity.java:
```
 startActivity(launchIntent.setFlags(Intent.FLAG_ACTIVITY_SINGLE_TOP));
```

Seems to work for me as it is, don't know if there are any use cases for you where this is not advisable?

**Comment by fidoboy** [comment]
Thanks @emc2spider! I'll try it ASAP

**Comment by fidoboy** [comment]
What steroids and CLI versions are you using with your tests? After this change I still receive the notification in task bar, even if my app is foreground. My app event is being triggered only when i replace the current webView. Changing the webView i receive the push notification event but the following notifications are not being received until i replace the webView again.

**Comment by emc2spider** [comment]
Hey @fidoboy I have: AppGyver Steroids² 4.0.8

The notification still arrives to the task bar but it doesn't get stuck at the splash screen trying to relaunch the main activity, so far I'm getting the notifications alright without replacing webViews. I think there are still a few duplicated notifications but since it has no effect on my app I haven't tried to pinpoint what's the cause or pattern.

**Comment by fidoboy** [comment]
Is your app MPA or SPA? Where are you receiving the notifications? is it the active (and visible) webView or is it a hidden webView (I'm using the initial view, that it's hidden). I'm only receiving the notification after I push or load a new webView, then no more notifications are being received in that same webView until I replace it with another one... :confounded:

**Comment by fidoboy** [comment]
Ok, forget it... problem solved; it was an issue with nested events in my code (it worked on iOS however, not sure why). Now all notifications are arriving fine to my app :smile: Only problem now is the task bar notifications being triggered even when the app is foreground

**Comment by jeffthompson1971** [comment]
I have this very same problem.   I would prefer to not have anything in my app bar when my app is in the foreground, but I'd be happy now just to stop getting the crash when i press it.  where exactly is the fix?  what version?  how do i pick it up?

**Comment by fidoboy** [comment]
I'm trying to fix the issue. There is a function named createNotification in GCMIntentService.java In theory the task bar notification is created here, isn't it? It's weird cause I'm commenting this out and i still have the task bar notify :unamused:

**Comment by fidoboy** [comment]
Ok, i've solved the problem! Please, disable the checkmark for push notifications on Appgyver build and add my repo to the plugins list to test it (https://github.com/fidoboy/PushNotifications.git). The only issue I'm having now is that the ```messageInForegroundHandler``` function in my app is not being triggered sometimes, but i believe that this is a issue with my code. 

I've also enhanced the plugin by adding custom icon feature. To use it, provide the icon image path with your push message using the key value 'icon'; if icon value is not used, then default app icon will be displayed. 

Not sure about how to make a pull request to add my changes enhancements into the main trunk. May be @harsaharsa could help here...

**Comment by fidoboy** [comment]
NOTE: if you use my plugin version on iOS you will notice that the notification object structure is a bit different from original (to solve also the missing custom properties with Appgyver plugin version) and you should use ```notification.aps.alert``` or ```notification.aps.sound``` to get the right values.

**Comment by emc2spider** [comment]
Thanks @fidoboy I'll check it up. Not sure the iOS structure changes are convenient for me though. The icon feature can be interesting to try :)

**Comment by fidoboy** [comment]
You could also try to merge @roberto-robles changes as proposed here: https://github.com/AppGyver/PushNotifications/pull/13 I believe that it's a better approach to get custom properties with iOS while keeping the original structure (and your code) working. I'm waiting for Appgyver team to merge all of this stuff and this way enhance the plugin using the best of all suggested changes by all of us

**Comment by fidoboy** [comment]
Main problem with the original Appgyver plugin code was that iOS version does not consider custom properties sent with your push message (if you are using any)

**Comment by emc2spider** [comment]
I'm receiving custom app data in my notifications just fine, not sure what I'm doing different there.

**Comment by fidoboy** [comment]
Using iOS? How?

**Comment by emc2spider** [comment]
I'm adding it on the notification object at the level of the alert and badge fields, as a JSON string.

**Comment by harsaharsa** [comment]
I took a good hard look at the Android PushNotification implementation today. While implementing your fixes (thanks for them!) I also discovered a few new bugs, but it's almost stable now. Just to let you know we're working on this!

**Comment by fidoboy** [comment]
Great @harsaharsa however I'm afraid that the 'deviceready' bug should be fixed to have the whole thing working

**Comment by jeffthompson1971** [comment]
Please GOD fix this 'deviceready' issue?    This should be the number one defect .. all hands on deck and no one goes home until this is  fixed!    I have totally stopped all development becuase this issue is breaking absolutely everything.   My oAuth no longer works.. the login screen comes up for 1 second and then dies... BUT if I put a button on my page so that i can wait for some time before i try to use it, THEN it's fine... clearly another timing issue due to this 'deviceready' not firing.  I'm also seeing like 23 log messages as 'steroids is undefined'.... until 'deviceready' issue is fixed how can we ever know what bugs are real bugs and what are just side effects of this massively awful bug?  This one bug cuts across every single user and every single app and IMHO should be the only thing worked on until its' 100% reliable..   nothing else matters at all. 

I really need an ETA for this issue.. if it's not going to be fixed this month i may be forced to scrap the last 8 months of work and start over with a new technology stack.   And I MAY loose my job for backing this for so long :(   please god focus on this and fix it.... and I need an ETA of when i can start my developers working again.  i have nothing for them to do while this issue exists.

Oh yeah.. I'd love to give feedback on this PushNotification fix, but I can't even get past authentication so I can't help ....

**Comment by pre** [comment]
Please try https://github.com/AppGyver/PushNotifications.git#next (notice the #next) with Android 4.0.5-edge6. If fixes many of the reported issues, please see the [changelog](https://github.com/AppGyver/PushNotifications/blob/next/CHANGELOG.md).

**Comment by emc2spider** [comment]
@pre just to be sure, this means we'll have to add this "#next" to both the plugin add command and the build service configurations?

**Comment by pre** [comment]
Yes, `#next` means that the plugin will be compiled from the `next` branch of that repository. The `master` branch doesn't yet contain these fixes. They will be merged when the next Android stable version is released.

**Comment by s-stude** [comment]
@fidoboy Hello, did you change something in the plugin? this does not work for me anymore.. It worked fine for my Scanner build two months ago, and scanner can receive push notifications in the background.. But now, the scanner build with this plugin does not show notifications for Android in the background..

**Comment by fidoboy** [comment]
In my fork? no, it's the same. It works fine for me.

**Comment by s-stude** [comment]
Well, at least there are some commits in August. My scanner build was
created in June, without your latest changes. Anyway, I tried to rollback
those commits and that didn't help..

I really don't know what to do..


--
Regards,
Akim Khalilov.

Akim.Khalilov@gmail.com
Cell: +7-978-881-29-10

Skype: Akim.Khalilov

**Comment by fidoboy** [comment]
But it's in my fork?

**Comment by s-stude** [comment]
I've cloned and pushed that to my account.. Didn't changed your..


--
Regards,
Akim Khalilov.

Akim.Khalilov@gmail.com
Cell: +7-978-881-29-10

Skype: Akim.Khalilov
